// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using CoreGraphics;
using Foundation;
using ObjCRuntime;
using UIKit;

namespace alat_kiddies_iOS1
{
	public partial class GuardianTxHistoryVC : UIViewController
    {
		public GuardianTxHistoryVC (IntPtr handle) : base (handle)
		{
		}
        UIDynamicAnimator animator;
        UIDynamicItemBehavior spinnerBehaviour;

        List<ParentTransaction> transactions = new List<ParentTransaction>
        {
            new ParentTransaction { transactionType = "Credit", transactionAmount = 10000, transactionRecipientAccount = "0956712345", transactionDate = "20/09/2022" },
            new ParentTransaction { transactionType = "Debit", transactionAmount = 1000011, transactionRecipientAccount = "0956732145", transactionDate = "20/09/2022" },
        };

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            parentTxHistoryTable.Source = new ParentTxHistorySource(transactions);
            //StartAmination();
        }        

        void StartAmination()
        {
            try
            {
                loadingTxHistoryView.Hidden = false;
                spinnerBehaviour = new UIDynamicItemBehavior(spinningIndicatorImg);
                animator = new UIDynamicAnimator(loadingTxHistoryView);
                spinnerBehaviour.AngularResistance = (nfloat)0.0;
                spinnerBehaviour.AddAngularVelocityForItem(8.0f, spinningIndicatorImg);
                animator.AddBehavior(spinnerBehaviour);


                UIImageView.Animate(2, 0, options: UIViewAnimationOptions.Repeat | UIViewAnimationOptions.Autoreverse, () =>
                {
                    alatLoadingImg.Transform = CGAffineTransform.MakeScale((nfloat)0.8, (nfloat)0.8);
                    alatLoadingImg.Transform = CGAffineTransform.MakeScale((nfloat)1, (nfloat)1);
                }, null);

                UIApplication.SharedApplication.BeginIgnoringInteractionEvents();
            }

            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }

        void StopAnimation()
        {
            animator.RemoveAllBehaviors();
            loadingTxHistoryView.Hidden = true;
            UIApplication.SharedApplication.EndIgnoringInteractionEvents();
        }

        
    }
}
