// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace alat_kiddies_iOS1
{
	public partial class ParentsDashBoardVC : UIViewController
	{
		public ParentsDashBoardVC (IntPtr handle) : base (handle)
		{
		}
	}
}
