// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Foundation;
using UIKit;

namespace alat_kiddies_iOS1
{
	public partial class ParentsDashBoardVC : UIViewController
	{
		public ParentsDashBoardVC(IntPtr handle) : base(handle)
		{
		}

		List<UIImage> animationImages = new List<UIImage>()
			{
				UIImage.FromBundle("caraouselImage1"),
				UIImage.FromBundle("caraouselImage2"),
				UIImage.FromBundle("caraouselImage3"),
			};

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			
			DbBckGrndImg.Layer.CornerRadius = 15;
			AccBalLbl.Text = "₦" + String.Format("{0:n}", 10000);
			AccNumLbl.Text = "1350234780";
			AccTypeLbl.Text = "Tier 3";
			nameLbl.Text = "Hi, Moses";

			FundAccBtn.Layer.BackgroundColor = CoreGraphics.CGColor.CreateSrgb(1, 244 / 255, 244 / 255, 1);
			FundAccBtn.Layer.CornerRadius = 15; 

			TxHistoryBtn.Layer.BackgroundColor = CoreGraphics.CGColor.CreateSrgb(1, 244 / 255, 244 / 255, 1);
			TxHistoryBtn.Layer.CornerRadius = 15;

			ShowHideImg.UserInteractionEnabled = true;
			sendMoneyImg.UserInteractionEnabled = true;
			createAccImg.UserInteractionEnabled = true;
			airtimeImg.UserInteractionEnabled = true;
			kiddiesImg.UserInteractionEnabled = true;

			ShowHideImg.AddGestureRecognizer(new UITapGestureRecognizer(HideBalance));
			sendMoneyImg.AddGestureRecognizer(new UITapGestureRecognizer(SendMoney));
			createAccImg.AddGestureRecognizer(new UITapGestureRecognizer(CreateAccount));
			airtimeImg.AddGestureRecognizer(new UITapGestureRecognizer(AirtimePurchase));
			kiddiesImg.AddGestureRecognizer(new UITapGestureRecognizer(RoyalKiddies));

			try
			{
				carouselView.Layer.CornerRadius = 15;
				carouselImg.Layer.CornerRadius = 15;
			}
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

			animateimages();
		}

		public async void animateimages()
		{
			pageControl.Pages = animationImages.Count;
			for (int i = 0; i <= animationImages.Count; i++)
			{
				if (i == 3)
				{
					i = 0;
					carouselImg.Image = animationImages[i];
					pageControl.CurrentPage = i;
					//break;
				}
				carouselImg.Image = animationImages[i];
				pageControl.CurrentPage = i;				
				await Task.Delay(2500);												
			}

		}



        private void RoyalKiddies()
        {
            throw new NotImplementedException();
        }

        private void AirtimePurchase()
        {
            throw new NotImplementedException();
        }

        private void CreateAccount()
        {
            throw new NotImplementedException();
        }

        private void SendMoney()
        {
            throw new NotImplementedException();
        }

        void HideBalance(UITapGestureRecognizer taprecognizer)
        {
			if (ShowHideImg.Image == UIImage.FromBundle("hide"))
			{
				AccBalLbl.Text = "₦"+"XXXXXX";
				ShowHideImg.Image = UIImage.FromBundle("show");
			}
			else
			{
				AccBalLbl.Text = "₦" + String.Format("{0:n}", 10000);
				ShowHideImg.Image = UIImage.FromBundle("hide");
			}
		}
    }
}
