// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace alat_kiddies_iOS1
{
	public partial class TransactionTableCell : UITableViewCell
	{
		public TransactionTableCell (IntPtr handle) : base (handle)
		{
		}

		public TransactionTableCell()
        {

        }

		public void PopulateCell(ParentTransaction transaction)
        {
			transactionAmountLbl.Text = "₦" + transaction.transactionAmount;
			transactionDateLbl.Text = transaction.transactionDate;
			transactionRecipientLbl.Text = transaction.transactionRecipientAccount;
			transactionTypeLbl.Text = transaction.transactionType;

			if (transaction.transactionType == "Debit")
            {
				transactionTypeLbl.TextColor = UIColor.Red;
            }

        }
	}
}
