// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace alat_kiddies_iOS1
{
	public partial class WardTxHistoryVC : UIViewController
	{
		public WardTxHistoryVC (IntPtr handle) : base (handle)
		{
		}
	}
}
