// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace alat_kiddies_iOS1.Kiddies
{
	public partial class WardTxHistoryScreen : UIViewController
	{
		public WardTxHistoryScreen (IntPtr handle) : base (handle)
		{
		}
	}
}
