// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace alat_kiddies_iOS1.Kiddies
{
	public partial class WardDashBoardScreen : UIViewController
	{
		public WardDashBoardScreen (IntPtr handle) : base (handle)
		{
		}

        string name = "Obaro";

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }

    }
}
